# Generated by Django 5.2.1 on 2025-08-15 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cajas',
            fields=[
                ('id_caja', models.AutoField(db_column='Id_caja', primary_key=True, serialize=False)),
                ('saldo_inicial', models.DecimalField(db_column='Saldo_inicial', decimal_places=5, max_digits=12)),
                ('saldo_anterior', models.DecimalField(db_column='Saldo_anterior', decimal_places=5, max_digits=12)),
                ('saldo_actual', models.DecimalField(db_column='Saldo_actual', decimal_places=5, max_digits=12)),
                ('saldo_final', models.DecimalField(db_column='Saldo_final', decimal_places=5, max_digits=12)),
                ('fecha_apertura', models.DateTimeField(db_column='Fecha_apertura')),
                ('fecha_cierre', models.DateTimeField(db_column='Fecha_cierre')),
                ('estado_caja', models.IntegerField(db_column='Estado_caja')),
            ],
            options={
                'db_table': 'cajas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id_cliente', models.AutoField(db_column='Id_cliente', primary_key=True, serialize=False)),
                ('nombre_cliente', models.CharField(db_column='Nombre_cliente', max_length=45)),
                ('apellido_cliente', models.CharField(db_column='Apellido_cliente', max_length=45)),
                ('correo_clientes', models.CharField(db_column='Correo_clientes', max_length=45)),
                ('telefono_cliente', models.CharField(db_column='Telefono_cliente', max_length=45)),
                ('dni_cliente', models.CharField(db_column='DNI_cliente', max_length=45)),
                ('estado_cliente', models.IntegerField(db_column='Estado_cliente')),
            ],
            options={
                'db_table': 'clientes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Compras',
            fields=[
                ('id_compra', models.AutoField(db_column='Id_compra', primary_key=True, serialize=False)),
                ('nombre_compra', models.CharField(db_column='Nombre_compra', max_length=455)),
                ('cantidad_compra', models.IntegerField(db_column='Cantidad_compra')),
                ('fecha_compra', models.DateField(db_column='Fecha_compra')),
                ('precio_compra', models.DecimalField(db_column='Precio_compra', decimal_places=5, max_digits=12)),
                ('descripcion_compra', models.CharField(db_column='Descripcion_compra', max_length=455)),
                ('estado_compra', models.IntegerField(blank=True, db_column='Estado_compra', null=True)),
            ],
            options={
                'db_table': 'compras',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetalleCompras',
            fields=[
                ('id_detalle_compra', models.AutoField(db_column='Id_detalle_compra', primary_key=True, serialize=False)),
                ('precio_unitario_dtc', models.DecimalField(db_column='Precio_unitario_dtc', decimal_places=5, max_digits=12)),
                ('subtotal_dtc', models.DecimalField(db_column='Subtotal_dtc', decimal_places=5, max_digits=12)),
                ('descuento_dtc', models.DecimalField(db_column='Descuento_dtc', decimal_places=5, max_digits=12)),
                ('total_dtc', models.DecimalField(db_column='Total_dtc', decimal_places=5, max_digits=12)),
                ('fecha_entrega_dtc', models.DateField(db_column='Fecha_entrega_dtc')),
                ('descripcion_dtc', models.CharField(blank=True, db_column='Descripcion_dtc', max_length=445, null=True)),
                ('estado_dtc', models.IntegerField(db_column='Estado_dtc')),
            ],
            options={
                'db_table': 'detalle_compras',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetalleSolicOc',
            fields=[
                ('id_detalle_solic_oc', models.AutoField(db_column='Id_detalle_solic_OC', primary_key=True, serialize=False)),
                ('cantidad_producto_oc', models.IntegerField(db_column='Cantidad_producto_OC')),
                ('precio_unitario_oc', models.DecimalField(db_column='Precio_unitario_OC', decimal_places=5, max_digits=12)),
                ('sub_total_oc', models.DecimalField(db_column='Sub_total_OC', decimal_places=5, max_digits=12)),
                ('fecha_oc', models.DateField(db_column='Fecha_OC')),
                ('decripcion_oc', models.CharField(db_column='Decripcion_OC', max_length=455)),
                ('estado_oc', models.IntegerField(db_column='Estado_OC')),
            ],
            options={
                'db_table': 'detalle_solic_oc',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id_emp', models.AutoField(db_column='Id_emp', primary_key=True, serialize=False)),
                ('nombre_emp', models.CharField(db_column='Nombre_emp', max_length=45)),
                ('apellido_emp', models.CharField(db_column='Apellido_emp', max_length=45)),
                ('dni_emp', models.CharField(db_column='DNI_emp', max_length=45)),
                ('direccion_emp', models.CharField(db_column='Direccion_emp', max_length=455)),
                ('telefono_emp', models.IntegerField(db_column='Telefono_emp')),
                ('correo_emp', models.CharField(db_column='Correo_emp', max_length=100)),
                ('estado_emp', models.IntegerField(db_column='Estado_emp')),
            ],
            options={
                'db_table': 'empleados',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmpRoles',
            fields=[
                ('id_rol_emp', models.AutoField(db_column='Id_rol_emp', primary_key=True, serialize=False)),
                ('estado_emp_rol', models.IntegerField(blank=True, db_column='Estado_emp_rol', null=True)),
            ],
            options={
                'db_table': 'emp_roles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mascotas',
            fields=[
                ('id_mascotas', models.AutoField(db_column='Id_mascotas', primary_key=True, serialize=False)),
                ('estado_mascota', models.IntegerField(blank=True, db_column='Estado_mascota', null=True)),
            ],
            options={
                'db_table': 'mascotas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrdenCompras',
            fields=[
                ('id_orden_compra', models.AutoField(db_column='Id_orden_compra', primary_key=True, serialize=False)),
                ('fecha_emision_orden', models.DateField(db_column='Fecha_emision_orden')),
                ('total_orden', models.DecimalField(db_column='Total_orden', decimal_places=5, max_digits=12)),
                ('estado_orden', models.IntegerField(db_column='Estado_orden')),
            ],
            options={
                'db_table': 'orden_compras',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PrecioServicios',
            fields=[
                ('id_precio_servicio', models.AutoField(db_column='Id_precio_servicio', primary_key=True, serialize=False)),
                ('precio_unitario_preser', models.DecimalField(db_column='Precio_unitario_preser', decimal_places=5, max_digits=12)),
                ('precio_completo_preser', models.DecimalField(db_column='Precio_completo_preser', decimal_places=5, max_digits=12)),
                ('descripcion_precio_servicio', models.CharField(blank=True, db_column='Descripcion_precio_servicio', max_length=455, null=True)),
                ('estado_precio_servicio', models.IntegerField(blank=True, db_column='Estado_precio_servicio', null=True)),
            ],
            options={
                'db_table': 'precio_servicios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id_prod', models.AutoField(db_column='Id_prod', primary_key=True, serialize=False)),
                ('nombre_prod', models.CharField(db_column='Nombre_prod', max_length=45)),
                ('stock_prod', models.CharField(db_column='Stock_prod', max_length=45)),
                ('precio_prod', models.DecimalField(db_column='Precio_prod', decimal_places=5, max_digits=12)),
                ('unidad_media_prod', models.CharField(db_column='Unidad_media_prod', max_length=45)),
                ('categoria_prod', models.CharField(db_column='Categoria_prod', max_length=45)),
                ('estado_prod', models.IntegerField(blank=True, db_column='Estado_prod', null=True)),
            ],
            options={
                'db_table': 'productos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Proveedoress',
            fields=[
                ('id_prov', models.AutoField(db_column='Id_prov', primary_key=True, serialize=False)),
                ('nombre_prov', models.CharField(db_column='Nombre_prov', max_length=45)),
                ('correo_prov', models.CharField(db_column='Correo_prov', max_length=45)),
                ('cuit_prov', models.IntegerField(db_column='CUIT_prov')),
                ('telefono_prov', models.IntegerField(db_column='Telefono_prov')),
                ('descripcion_prov', models.CharField(db_column='Descripcion_prov', max_length=455)),
                ('estado_prov', models.IntegerField(blank=True, db_column='Estado_prov', null=True)),
            ],
            options={
                'db_table': 'proveedoress',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Provxprod',
            fields=[
                ('id_provxprod', models.AutoField(db_column='Id_provXprod', primary_key=True, serialize=False)),
                ('estado_provxprod', models.IntegerField(blank=True, db_column='Estado_provXprod', null=True)),
                ('nombre_prov', models.CharField(db_column='Nombre_prov', max_length=455)),
                ('nombre_prod', models.CharField(db_column='Nombre_prod', max_length=455)),
                ('fecha_entrega_provxprod', models.DateField(db_column='Fecha_entrega_provXprod')),
                ('descripcion_provxprod', models.CharField(db_column='Descripcion_provXprod', max_length=455)),
            ],
            options={
                'db_table': 'provxprod',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id_rol', models.AutoField(db_column='Id_rol', primary_key=True, serialize=False)),
                ('nombre_rol', models.CharField(db_column='Nombre_rol', max_length=95)),
            ],
            options={
                'db_table': 'roles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('id_servicio', models.AutoField(db_column='Id_servicio', primary_key=True, serialize=False)),
                ('nombre_servicio', models.CharField(db_column='Nombre_servicio', max_length=45)),
                ('descripcion_servicio', models.CharField(db_column='Descripcion_servicio', max_length=455)),
                ('tipo_servicio', models.CharField(db_column='Tipo_servicio', max_length=45)),
                ('estado_servicio', models.IntegerField(blank=True, db_column='Estado_servicio', null=True)),
            ],
            options={
                'db_table': 'servicios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ServiciosPrestados',
            fields=[
                ('id_serv_prest', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_serv_prest', models.CharField(max_length=45)),
                ('apellido_serv_prest', models.CharField(db_column='Apellido_serv_prest', max_length=45)),
                ('dni_serv_prest', models.IntegerField(db_column='DNI_serv_prest')),
                ('fecha_naci_serv_prest', models.DateField(db_column='Fecha_naci_serv_prest')),
                ('estado_serv_prest', models.IntegerField(blank=True, db_column='Estado_serv_prest', null=True)),
            ],
            options={
                'db_table': 'servicios_prestados',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SolicitudOrdenCompras',
            fields=[
                ('id_solicitud_orden_compra', models.AutoField(db_column='Id_solicitud_orden_compra', primary_key=True, serialize=False)),
                ('fecha_solicitud_orc', models.DateField(db_column='Fecha_solicitud_orc')),
                ('descripcion_orc', models.CharField(db_column='Descripcion_orc', max_length=455)),
                ('estado_orc', models.IntegerField(db_column='Estado_orc')),
            ],
            options={
                'db_table': 'solicitud_orden_compras',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('id_stock', models.AutoField(db_column='Id_stock', primary_key=True, serialize=False)),
                ('cantidad_stock', models.IntegerField(db_column='Cantidad_stock')),
                ('fecha_egreso_stock', models.DateTimeField(db_column='Fecha_egreso_stock')),
                ('fecha_vencimiento_stock', models.DateTimeField(db_column='Fecha_vencimiento_stock')),
                ('estado_stock', models.IntegerField(db_column='Estado_stock')),
            ],
            options={
                'db_table': 'stocks',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Turnos',
            fields=[
                ('id_turno', models.AutoField(db_column='Id_turno', primary_key=True, serialize=False)),
                ('fecha_turno', models.DateField(db_column='Fecha_turno')),
                ('hora_turno', models.TimeField(db_column='Hora_turno')),
                ('motivo_cance_turno', models.CharField(blank=True, db_column='Motivo_cance_turno', max_length=255, null=True)),
                ('estado_turno', models.IntegerField(db_column='Estado_turno')),
            ],
            options={
                'db_table': 'turnos',
                'managed': False,
            },
        ),
    ]
